=== tuiSSE/e4sm-editor/scripts/import-intermiediate-language/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "id": "https://sse.tu-ilmenau.de/intermediate/schemas/1",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the model, it shall not start with a number and shall not contain a |",
      "pattern": "^([a-z]|[A-Z]|_)[^|]*$"
    },
    "timestamp": {
      "type": "number"
    },
    "components": {
      "description":"An array of components",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "description": "A model-unique ID for this component, it shall not contain a |",
            "type": "string",
            "pattern": "^[^|]*$"
          },
          "name": {
            "type": "string",
            "description": "The name of the component, it shall not start with a number and shall not contain a |",
            "pattern": "^([a-z]|[A-Z]|_)[^|]*$"
          },
          "outputSize": {
            "description": "A formula computing the size of the output",
            "type": "string"
          },
          "inputPins": {
            "description":"An array of input pin objects",
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "string",
                  "description": "The name of the input pin, it shall not start with a number and shall not contain a |",
                  "pattern": "^([a-z]|[A-Z]|_)[^|]*$"
                }
              },
              "required": [
                "id"
              ]
            }
          },
          "outputPins": {
            "description":"An array of output pin objects",
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "string",
                  "description": "The name of the output pin, it shall not start with a number and shall not contain a |",
                  "pattern": "^([a-z]|[A-Z]|_)[^|]*$"
                },
                "dataFunction": {
                  "type": "string"
                }
              },
              "required": [
                "id"
              ]
            }
          },
          "executionFunction": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "meanValue": {
                "type": "string"
              },
              "variance": {
                "type": "number"
              },
              "maxError": {
                "type": "number"
              }
            },
            "required": [
              "meanValue"
            ]
          },
          "parameters": {
            "description": "An array of parameters",
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The name of the parameter, it shall not start with a number and shall not contain a |",
                  "pattern": "^([a-z]|[A-Z]|_)[^|]*$"
                },
                "type": {
                  "enum": [
                    "int",
                    "real",
                    "string",
                    "bool",
                    "DateTime"
                  ]
                },
                "value": {
                  "description": "The value of the given parameter for this simulation (number, string or boolean)",
                  "type": [
                    "number",
                    "string",
                    "boolean"
                  ]
                }
              },
              "required": [
                "name",
                "value"
              ]
            }
          }
        },
        "required": [
          "id",
          "name",
          "executionFunction"
        ]
      }
    },
    "connections": {
      "description":"An array of connectors",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "source": {
            "type": "string"
          },
          "target": {
            "type": "string"
          },
          "transferTime": {
            "type": "number"
          }
        },
        "required": [
          "source",
          "target"
        ]
      }
    },
    "sources": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "description": "A model-unique ID for this source, it must not contain a |",
            "type": "string",
            "pattern": "^[^|]*$"
          },
          "name": {
            "type": "string",
      		"description" : "The name of the source, it shall not start with a number and shall not contain a |",
      		"pattern": "^([a-z]|[A-Z]|_)[^|]*$"
          },
          "outputSize": {
            "description": "A formula computing the size of the output",
            "type": "string"
          },
          "outputPins": {
            "description":"An array of output pin objects",
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "string",
                  "pattern": "^([a-z]|[A-Z]|_).*"
                },
                "dataFunction": {
                  "type": "string"
                },
                "results": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "value": {
                        "type": "number"
                      },
                      "probability": {
                        "type": "number"
                      },
                      "outputSize":{
                        "type":"number"
                      }
                    }
                  }
                }
              },
              "required": [
                "id"
              ]
            }
          },
          "executionFunction": {
            "type": "object",
            "properties": {
              "meanValue": {
                "type": ["string", "number"]
              },
              "variance": {
                "type": "number"
              },
              "maxError": {
                "type": "number"
              }
            },
            "required": [
              "meanValue"
            ]
          },
          "parameters": {
            "description": "An array of parameters",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "description": "The name of the parameter",
                  "type": "string"
                },
                "type": {
                  "enum": [
                    "int",
                    "real",
                    "string",
                    "bool",
                    "DateTime"
                  ]
                },
                "value": {
                  "description": "The value of the given parameter for this simulation (number, string or boolean)",
                  "type": [
                    "number",
                    "string",
                    "boolean"
                  ]
                }
              },
              "required": [
                "name",
                "value",
                "type"
              ]
            }
          }
        }
      },
      "required": [
        "id",
        "name",
        "executionFunction"
      ]
    }
  },
  "required": [
    "name",
    "components",
    "sources",
    "connections"
  ]
}

=== tuiSSE/e4sm-editor/scripts/import-intermiediate-language/tests/success.json
{
   "name":"StreamVizzard ILM",
   "timestamp":1682331357,
   "components":[
      {
         "id":"40",
         "name":"Canny",
         "parameters":[
            {
               "name":"aperture",
               "value":3
            }
         ],
         "executionFunction":{
            "meanValue":"-4.266610796018323 + 1.3137976680172652e-05 * $total + 0.6760845642177957 * @aperture",
            "variance":2.0159689200944957,
            "maxError":11.654133085123132
         },
         "outputSize":"354.677486210363 + 0.9999999933811271 * $total + -0.0 * @aperture",
         "inputPins":[
            {
               "id":"IN_0"
            }
         ],
         "outputPins":[
            {
               "id":"OUT_0",
               "dataFunction":"$IN_0"
            }
         ]
      },
      {
         "id":"41",
         "name":"Convert",
         "parameters":[
            {
               "name":"mode",
               "value":0
            }
         ],
         "executionFunction":{
            "meanValue":"-0.23820918448344885 + 5.167030556933668e-07 * $total + 0.00029333309214724335 * @mode + 2.3309370926483108e-14 * $total^2 + 2.071078968080256e-06 * $total * @mode + 0.0005866663780098715 * @mode^2",
            "variance":0.9523814716318486,
            "maxError":8.361485388490717
         },
         "outputSize":"354.8536443654448 + 0.999999919821921 * $total + 1.39875906892971 * @mode + 8.881784197001252e-16 * $total^2 + 5.500000074748424 * $total * @mode + 2.7975276548423658 * @mode^2",
         "inputPins":[
            {
               "id":"IN_0"
            }
         ],
         "outputPins":[
            {
               "id":"OUT_0",
               "dataFunction":"$IN_0"
            }
         ]
      },
      {
         "id":"42",
         "name":"GaussianBlur",
         "parameters":[
            {
               "name":"kernelX",
               "value":3
            },
            {
               "name":"kernelY",
               "value":3
            }
         ],
         "executionFunction":{
            "meanValue":"0.48201845283226064 + 2.3100401987878667e-06 * $total + -0.03724088642599941 * @kernelX + -0.0690229848327895 * @kernelY + -1.8887669206435476e-13 * $total^2 + 3.444872952702177e-08 * $total * @kernelX + 5.5155397128347624e-08 * $total * @kernelY + 0.001281522936401859 * @kernelX^2 + 0.0006730724240369734 * @kernelX * @kernelY + 0.0013625606843273327 * @kernelY^2",
            "variance":1.0934230848447095,
            "maxError":3.805689001135712
         },
         "outputSize":"370.5205499938688 + 2.9999999857695516 * $total + 0.002250241348965583 * @kernelX + 0.007714879764670351 * @kernelY",
         "inputPins":[
            {
               "id":"IN_0"
            }
         ],
         "outputPins":[
            {
               "id":"OUT_0",
               "dataFunction":"$IN_0"
            }
         ]
      }
   ],
   "sources":[
      {
         "id":"39",
         "name":"VideoFile",
         "executionFunction":{
            "meanValue":33,
            "variance":0,
            "maxError":0
         },
         "outputPins":[
            {
               "id":"OUT_0",
               "results":[
                  {
                     "value":2073600,
                     "probability":0.55,
                     "outputSize":2073954
                  },
                  {
                     "value":1920000,
                     "probability":0.25,
                     "outputSize":1920354
                  },
                  {
                     "value":432000,
                     "probability":0.1,
                     "outputSize":432354
                  },
                  {
                     "value":3686400,
                     "probability":0.1,
                     "outputSize":3686754
                  }
               ]
            }
         ]
      }
   ],
   "connections":[
      {
         "source":"VideoFile|39.OUT_0",
         "target":"Canny|40.IN_0",
         "transferTime":0.01
      },
      {
         "source":"Canny|40.OUT_0",
         "target":"Convert|41.IN_0",
         "transferTime":0.01
      },
      {
         "source":"Convert|41.OUT_0",
         "target":"GaussianBlur|42.IN_0",
         "transferTime":0.01
      }
   ]
}
